### ISSUE TITLE
reify and buildIdealTree(complete): refresh dep metadata if working from an old lockfile

### ISSUE THREAD

**Issue by isaacs** [npm/arborist#113]
See https://github.com/npm/cli/issues/1651

In `buildIdealTree({ complete: true })` and `reify()`, if the lockfile is `lockfileVersion: 1`, and there was no `node_modules` folder for `loadVirtual` to refresh metadata from, then we have to refresh dep metadata from the registry, even if we're not updating the node in question.

If we don't do this at the reify/buildIdealTree(complete) phase, then we'll save the lockfile back with `lockfileVersion: 2`, and never know that we have to update again in the future.

**Comment by MylesBorins** [comment]
Some weird stuff is also happening when installing sax which has an oolllllllld package lock

**Comment by isaacs** [comment]
example lockfile: https://github.com/isaacs/sax-js/blob/5aee216/package-lock.json

**Comment by isaacs** [comment]
Fixed in 0.0.17
