### ISSUE TITLE
[FEATURE] Add support to plugin dependencies.

### ISSUE THREAD

**Issue by mshima** [npm/arborist#121]
# What / Why

> I am calling plugin dependencies, dependencies that can be installed at runtime.

- Plugin dependencies should be installed at root level.
- They need to be installed with global style, so the node_modules tree won't mutate.
- Can be managed by the application that installed it.
  - If supported by package.json, can be ignored by `npm ci`, and force by `npm ci --with-plugins`.
- It would be great to have it inside package-lock.json for reproducibility.

In this use case I will focus on yeoman project generation.
Consider the example:
```
mkdir new-project
cd new-project
npm install yo --save-dev
npx yo node --experimental
```

- `npx yo node` is using a generator called `node` that is provided by `generator-node` package.
- `--experimental` flag uses an auto install feature that installs `generator-node` inside a hidden global-style node_modules.
  - Once installed, `yo` loads it and executes.
  - `yo` is running so if we mutate current node_modules, it will break.
  - `node` generator can install another generator, so if we mutate the hidden node_modules will break `node` generator.

**Comment by isaacs** [comment]
This should almost certainly be proposed and discussed over at https://github.com/npm/rfcs

Can you open an issue or PR over there and reference this one?  Closing for now, but happy to reopen (or create a new one) here once we land on a direction for this.

Thanks!
