### ISSUE TITLE
warn/throw on mismatched engine/platform all the time, not only for newly added modules

### ISSUE THREAD

**Issue by isaacs** [npm/arborist#134]
See https://github.com/npm/rfcs/pull/195

- Currently we call `checkEngine()`/`checkPlatform()` in `lib/arborist/reify.js`, but only for nodes being added to the tree in `reifyNode()`.
- _Either_ move that check to `loadActual` and `loadVirtual`, so that we can warn when we're initially building the tree, _or_ put it in `buildIdealTree` since we only care about it when we're going to be modifying stuff?  (Ie, should `npm ls` warn about it?  Should `npm ls --engines-strict` fail entirely and not even show a tree?)
- Since it's probably too aggressive to fail entirely if a package in the virtual/actual tree has an engine/platform mismatch, we can collect these errors up to the top level, and then have `buildIdealTree()` decide to throw if there are any engine mismatches and `options.enginesStrict` is true.

**Comment by isaacs** [comment]
Also: we should track the node/npm version in the package lock, and only run this check (at least in loadVirtual) if it doesn't match the current node/npm versions.

**Comment by markablov** [comment]
@isaacs should i implement that by my own? `arborist` looks not very familiar to me, but i think i can handle that.

**Comment by bonkydog** [comment]
Hi, @markablov. Thanks, but I just started working on this yesterday.

**Comment by darcyclarke** [comment]
Should land in the next beta release. Work landed in arborist here: https://github.com/npm/arborist/pull/138

**Comment by bonkydog** [comment]
Oh, wait, there's actually a patch on the CLI repo I need to get merged for this -- it fixes a bug in error message generation for platform mismatches.  I'll get it in today.

**Comment by darcyclarke** [comment]
@bonkydog noticed you reopened this, I think you mentioned there was a bug in this work yesterday that you were fixing but I didn't see any mention here. Can we use either a draff/WIP PR or net-new issue to track that fix?

**Comment by bonkydog** [comment]
Sorry, yeah this is closed.  I re-opened it by mistake.

There's an error message fix on CLI here ready for review:

https://github.com/npm/cli/pull/1876
