### ISSUE TITLE
TypeError: Cannot read property 'matches' of undefined. Is this a known issue?

### ISSUE THREAD

**Issue by DeveloperHIT** [npm/arborist#164]
I am getting an error when installing Gatsby-cli. The install breaks at the installation of arborist/lib/arborist/build-ideal-tree.js

1840 verbose stack TypeError: Cannot read property 'matches' of undefined
1840 verbose stack     at Arborist.[canPlaceDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1284:15)
1840 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:36)
1840 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1212:41)
1840 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:46
1840 verbose stack     at Array.map (<anonymous>)
1840 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:8)
1840 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:202:7)
1840 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
1840 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:40:5)

**Comment by igorakkerman** [comment]
I'm getting the error as well after upgrading to Node.js 15, which ships npm 7. As a workaround, I downgraded to npm 6, I can now install `gatsby-cli`:
```
npm i -g npm@latest-6
npm i -g gatsby-cli
```

**Comment by ljharb** [comment]
Which exact npm version? node v15.0.1 comes with npm v7.0.3

**Comment by igorakkerman** [comment]
I tried both npm 15.0.0 and npm 15.0.1 with their respected npm versions 7.0.2 and 7.0.3.

**Comment by igorakkerman** [comment]
The combination of npm 7.0.6 with the latest gatsby-cli seems to work.

**Comment by ejmurra** [comment]
I'm also getting this error using narwhal cli. Node v. 15.0.1, npm v 7.0.7

**Comment by igorakkerman** [comment]
Try to remove _node_modules/_ and clear all caches. Make sure, the latest _gatsby-cli_ is pulled.

**Comment by ejmurra** [comment]
clearing node modules did not work for me but reverting to npm v6.x did which I'm happy to use for the time being until this has been patched. Also fwiw, I am hitting this error trying to use a CLI that is not gatsby so it doesn't seem to be a gatsby specific error.

**Comment by ruyadorno** [comment]
Should have been fixed in #174 that went out on `npm@7.0.8` let us know if you still get a `TypeError: Cannot read property 'matches' of undefined` error 😊
