### ISSUE TITLE
[FEATURE?] (Documentation) Clearer first few paragraphs on the readme

### ISSUE THREAD

**Issue by Lazerbeak12345** [npm/arborist#168]
# What / Why
Upon finding this project on GitHub I could only hardly understand what it does via the readme.

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Expected Behavior
Perhaps you could contact the producer of [this article](https://blog.npmjs.org/post/618653678433435649/npm-v7-series-arborist-deep-dive) and include some of the content from there. It's much clearer about _what_ this does, and _why_ (with a touch of how).

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment]
Yes, I'll see if I can track down that author ;)

Been pretty busy making this thing behave properly and fix the bugs folks are finding with it in npm v7.  Docs are definitely on the todo list for the next month, though (both in npm/cli itself, and here).
