### ISSUE TITLE
[BUG] Reinstalling npm fails on Docker

### ISSUE THREAD

**Issue by ttshivers** [npm/arborist#169]
# What / Why
This appears to be a regression of https://github.com/npm/npm/pull/15901
In npm v6.14.8, all the installation logic used moves instead of renames for this reason after the above PR: https://github.com/npm/cli/tree/v6.14.8/lib/install/action

Now, in this repo, renames are used again: https://github.com/npm/arborist/blob/87a9fa922d6129e3be7f1ab3441eea2bb5d65466/lib/arborist/reify.js#L254

https://github.com/npm/npm/issues/9863#issuecomment-152342020
>From the aufs manual:
>>To rename(2) directory may return EXDEV even if both of src and tgt are on the same aufs. When the rename-src dir exists on multiple branches and the lower dir has child(ren), aufs has to copyup all his children. It can be recursive copyup. Current aufs does not support such huge copyup operation at one time in kernel space, instead produces a warning and returns EXDEV. Generally, mv(1) detects this error and tries mkdir(2) and rename(2) or copy/unlink recursively. So the result is harmless. If your application which issues rename(2) for a directory does not support EXDEV, it will not work on aufs. Also this specification is applied to the case when the src directroy exists on the lower readonly branch and it has child(ren).

## When
It looks like this started being an issue as of npm v7, which is when it split its entire Installer logic into this repo. https://github.com/npm/cli/blob/latest/CHANGELOG.md#v700-beta0-2020-08-04

## Where

* n/a

### Current Behavior
```console
$ docker run -it node:15.0.1 npm install -g npm@7.0.5
npm notice 
npm notice New patch version of npm available! 7.0.3 -> 7.0.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.0.5
npm notice Run npm install -g npm@7.0.5 to update!
npm notice 
npm ERR! code EXDEV
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -18
npm ERR! EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-24T01_54_22_453Z-debug.log
```

<details>
<summary>Detailed log</summary>
<pre>
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'npm@7.0.5'
0 verbose cli ]
1 info using npm@7.0.3
2 info using node@v15.0.1
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 5ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 16ms
19 verbose npm-session 00f2b133e05fdbcc
20 timing npm:load Completed in 46ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 4ms
23 timing idealTree:userRequests Completed in 19ms
24 silly idealTree buildDeps
25 silly fetch manifest npm@7.0.5
26 http fetch GET 200 https://registry.npmjs.org/npm 81ms (from cache)
27 silly placeDep ROOT npm@7.0.5 OK for:  want: 7.0.5
28 timing idealTree:#root Completed in 155ms
29 timing idealTree:node_modules/npm Completed in 0ms
30 timing idealTree:buildDeps Completed in 159ms
31 timing idealTree:fixDepFlags Completed in 3ms
32 timing idealTree Completed in 187ms
33 timing reify:loadTrees Completed in 798ms
34 timing reify:diffTrees Completed in 9ms
35 silly reify mark retired [
35 silly reify   '/usr/local/lib/node_modules/npm',
35 silly reify   '/usr/local/bin/npm',
35 silly reify   '/usr/local/bin/npx'
35 silly reify ]
36 silly reify moves {
36 silly reify   '/usr/local/lib/node_modules/npm': '/usr/local/lib/node_modules/.npm-i9nnxROI',
36 silly reify   '/usr/local/bin/npm': '/usr/local/bin/.npm-uJtxIR1m',
36 silly reify   '/usr/local/bin/npx': '/usr/local/bin/.npx-xXo12k2C'
36 silly reify }
37 timing reify:rollback:retireShallow Completed in 27831ms
38 timing command:install Completed in 28651ms
39 verbose stack Error: EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
40 verbose cwd /
41 verbose Linux 5.4.0-52-generic
42 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@7.0.5"
43 verbose node v15.0.1
44 verbose npm  v7.0.3
45 error code EXDEV
46 error syscall rename
47 error path /usr/local/lib/node_modules/npm
48 error dest /usr/local/lib/node_modules/.npm-i9nnxROI
49 error errno -18
50 error EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
51 verbose exit -18
</pre>
</details>

### Steps to Reproduce
```console
docker run -it node:15.0.1 npm install -g npm@7.0.5
```

### Expected Behavior
I expect npm to be able to reinstall on docker with aufs.

## Who

* n/a

## References
https://github.com/npm/npm/pull/15901
https://github.com/npm/npm/issues/9863
https://github.com/npm/cli/issues/606
https://github.com/npm/cli/issues/2031
https://github.com/nodejs/docker-node/issues/1379

**Comment by nikolaik** [comment]
Also being hit by this when trying to upgrade to the latest npm v7 using `npm i -g npm@^7` in node v15 docker images. Using the workaround detailed [here](https://blog.cloud66.com/using-node-with-docker/) still works:
```dockerfile
RUN mv /usr/local/lib/node_modules /usr/local/lib/node_modules.tmp && mv /usr/local/lib/node_modules.tmp /usr/local/lib/node_modules && npm i -g npm@^7
```

**Comment by isaacs** [comment]
Fixed in latest npm release.

**Comment by rickhull** [comment]
For reference, I believe this is fixed by https://github.com/npm/arborist/pull/176
