### ISSUE TITLE
Create logger class

### ISSUE THREAD

**Issue by darcyclarke** [npm/arborist#18]

**Comment by isaacs** [comment]
It might be a good idea to not have "logging" per se in Arborist at all, but instead just have the Arborist class emit some events for various things that happen in the lifecycle of tree maintenance.  Then the cli can decide what to log on.  Emitting events is way cheaper than actually writing to stdout, and avoids Yet Another config goober that Arborist has to pass around.

**Comment by claudiahdz** [comment]
Is it ok to close this issue in favor of: https://github.com/npm/arborist/issues/24 ?

**Comment by isaacs** [comment]
Yes, this is as done as it's going to be.  We can revisit how we handle logging throughout the CLI stack at a future time.
