### ISSUE TITLE
[BUG] Consistent resolve.js always returns git+ssh, no matter what protocol was used

### ISSUE THREAD

**Issue by drewpc** [npm/arborist#196]
# What / Why
An entry in package.json with a `git+https` URL, such as `git+https://git@github.com/a/b.git` is always transformed into an SSH URL by Arborist and saved as `git+ssh://git@github.com/a/b.git`.  This can be a problem if people have specific authentication keys setup for one protocol or another.

## When
* All `git+` URLs get transformed to `git+ssh` instead of retaining their protocol (if specified)

## Where
* URLs specified in package.json when saving to package-lock.json

### Current Behavior
* Add a `git+https` URL to package.json and save the package-lock.json.  The URL will be converted to `git+ssh` in package-lock.json

### Steps to Reproduce
* Add a `git+https` URL to package.json and save the package-lock.json.  The URL will be converted to `git+ssh` in package-lock.json

### Expected Behavior
* A `git+https` URL in package.json is correctly formatted and the protocol is retained in package-lock.json

## References
* Related to https://github.com/npm/cli/issues/2389

**Comment by isaacs** [comment]
Fixed by npm/arborist@9989f4f
