### ISSUE TITLE
[QUESTION] How to access information about the package what was added/installed

### ISSUE THREAD

**Issue by derberg** [npm/arborist#243]
# What / Why

I want to use arborist in docs/code generator that allows user to provide a template as a reference to npm package:

```
generator ./filepath.yml @mynpm/package
```

Atm we use `npmi` because we needed a tool that at the end of the template installation, provides information about the added package, like name, version, and install path. We want to use Arborist now but I'm not that familiar working with `Symbol` and I try to figure out how to do it.

## Where

This is how I did it for now:
```
      const installResult = await arb.reify({
        add: ['https://github.com/asyncapi/markdown-template'],
        saveType: 'prod',
        save: false,
      });
      const packageName = arb[Symbol.for('resolvedAdd')][0].name;
      
      console.log(packageName);  // @asyncapi/markdown-template
      console.log(installResult.children.get(packageName).version); //0.12.0
      console.log(installResult.children.get(packageName).path); ///Users/<user>/generator/node_modules/@asyncapi/markdown-template
```

my biggest concern is `Symbol.for('resolvedAdd')` this the right way? or is there something better, something in the API that I kinda missed?

Thanks a lot in advance 🙏🏼

**Comment by isaacs** [comment]
Definitely you should not be diving into the Symbol properties, those are internal, and subject to change without warning between versions.

The most definitive way to get a list of what was added would be to look at `arb.diff`, which is a Diff object containing a tree of which nodes were added/removed/changed.

However, that won't necessarily tell you _why_ they were mutated.  If you do `reify({ add: [pkg] })`, then there might be a whole bunch of `ADD` actions within the diff object, for all of the pkg's dependencies that landed at the top level.

If you just want to resolve a single package specifier to a name and version, it might be helpful to use `pacote` for this.

```js
const pacote = require('pacote')
const Arborist = require('@npmcli/arborist')

const arb = new Arborist({ ... })
const request = 'https://github.com/asyncapi/markdown-template'
const manifest = pacote.manifest(request)
const tree = await arb.reify({
  add: [request],
  saveType: 'prod', // why are you setting saveType...
  save: false, // when save=false?
})

console.log(arb.explicitRequests) // public list of what was requested

const packageName = manifest.name
const node = tree.children.get(packageName)
const { path, version } = node
assert.equal(version, manifest.version) // could get from either one, really
```

Does any of that get you pointed in a more useful direction?
