### ISSUE TITLE
[BUG] npm install recursively changes the owner of all files in my project, crashing mysql in docker

### ISSUE THREAD

**Issue by hartbit** [npm/arborist#252]
# What / Why

Since recent versions of npm, running `npm install` has been recursively changing the owner of all files in my project. Some of these files (the mysql data volumes) are owned by a `docker` user, and that change of owner crashes the mysql container.

I've been able to track down that behavior to the following line of code that was added recently:

https://github.com/npm/arborist/blob/main/lib/arborist/reify.js#L149

- Shouldn't `npm` only be concerned about the `node_modules` folder and the few files  like `package.json` ?
- Changing the owner of files that are out of the purview of `npm` sounds like a bug.

## When

Whenever I run npm install.

**Comment by Zmaon** [comment]
+ 1, this is an issue for us and we've been forced to downgrade to an earlier version of npm.
