### ISSUE TITLE
[QUESTION] How is the install algorithm supposed to work ?

### ISSUE THREAD

**Issue by Badisi** [npm/arborist#316]
Original issue: [npm/cli#3724](https://github.com/npm/cli/issues/3724)

> I originally reported a bug on the cli repository, but looking at the [changelog](https://github.com/npm/cli/blob/latest/CHANGELOG.md#v7203-2021-07-29) of the cli, I figured that it was maybe more related to `arborist` (since `npm@7.20.3` upgraded `arborist` to `v2.8.0`).

-----

### Current Behavior

So I have a specific case where the npm's install algorithm changed between `npm@7.20.2` and `npm@7.20.3`.

I have a devDependency (**A**) which itself has its own dependencies (**B**).
With `npm@7.20.2` all of the dependencies (**B**) are installed at the top-level node_modules of my project (which seems normal according to the [documentation](https://docs.npmjs.com/cli/v7/commands/npm-install#algorithm)).
But with `npm >= 7.20.3` all of the dependencies (**B**) are installed privately inside (**A**) without even existing at the top-level node_modules. I thought that deps were installed to top-level by default and privately only if found under another version at the top-level.

What's even weird, is that removing `typescript` from the `package.json` makes everything works the same way as with `npm@7.20.2`. Like if `typescript` was the one completely changing the node_modules layout.

And I also try making **B** both as `dependencies` and `peerDependencies` of **A** but without luck.

Any advices on how and why it is now behaving like that would be very appreciated 🙏
Thanks!

### Steps to reproduce

Given the following **package.json** :
```json
{
    "devDependencies": {
        "@hug/eslint-config": "^3.1.2",
        "typescript": "~4.3.5"
    }
}
```
Running `npm install` produces:
```sh
# With npm 7.20.2
node_modules
├── @angular-eslint
│   └── builder
├── @hug
│   └── eslint-config
├── eslint-plugin-rxjs
├── eslint-plugin-rxjs-angular
└── ...

# With npm >= 7.20.3
node_modules
├── @hug
│   └── eslint-config
│       └── node_modules
│           ├── @angular-eslint
│           │   └── builder
│           ├── eslint-plugin-rxjs
│           ├── eslint-plugin-rxjs-angular
│           └── ...
└── ...
```

### Environment

- OS: macOS Catalina (version 10.15.6)
- Node: 14.17.5
- npm: 7.22.0

**Comment by lukekarrys** [comment]
@Badisi I'm going to close this one. I think the proper place for this is the original issue you opened (https://github.com/npm/cli/issues/3724) since the best fix is probably updating the npm docs.
