### ISSUE TITLE
[BUG] nebulous error when using arborist in a path with no `package.json`

### ISSUE THREAD

**Issue by mikemimik** [npm/arborist#51]
# What / Why

```
npm verb stack TypeError: Cannot read property 'name' of null
npm verb stack     at npa (/Users/mperrotte/npminc/cli/node_modules/npm-package-arg/npa.js:28:20)
npm verb stack     at FetcherBase.get (/Users/mperrotte/npminc/cli/node_modules/pacote/lib/fetcher.js:448:16)
npm verb stack     at Object.extract (/Users/mperrotte/npminc/cli/node_modules/pacote/lib/index.js:4:34)
npm verb stack     at Arborist.[extractOrLink] (/Users/mperrotte/npminc/cli/node_modules/@npmcli/arborist/lib/arborist/reify.js:344:16)
npm verb stack     at p.(anonymous function).then (/Users/mperrotte/npminc/cli/node_modules/@npmcli/arborist/lib/arborist/reify.js:330:39)
```
Get this nebulous error when trying to run `arborist.buildIdealTree` and `arborist.reify` in a path that doesn't contain a `package.json`

## When

- Running `.buildIdealTree()`
- Running `.reify()`

## Where

- `opts = { path: 'some/path/with/no/package/json' }`

### Current Behavior

- Nebulous error

### Expected Behavior

- Should throw with intelligent error message which can be caught and used

**Comment by mikemimik** [comment]
Test would look something like:

```javascript
t.test('fail nicely without package.json', t => {
  const path = t.testdir()
  return t.rejects(new Arborist({ path }).buildIdealTree(), {code: 'ENOENT', path: resolve(path, 'package.json') })
})
```

**Comment by isaacs** [comment]
This appears to be working as intended now.  buildIdealTree and reify both succeed.  reify saves an empty package.json, buildIdealTree says "yep, nothing goes here, all good".
