### ISSUE TITLE
Arborist API refactor

### ISSUE THREAD

**Issue by isaacs** [npm/arborist#6]
Default export should be Arborist class, not loadActual (carry-over from read-package-tree)

**Comment by isaacs** [comment]
move the logic from `lib/load-actual.js` into the Arborist class, use that object as the place to hang all the state like caches etc.  Then we can also have a unified createNode and createLink method, which will be good to share between the physical and logical forms.

**Comment by dhuang612** [comment]
can I take this on?

**Comment by isaacs** [comment]
Hi, @dhuang612.  I think this is actually landed in the master branch already, now that I look at it.  Since arborist is entirely green field, and will be the major part of the work for npm v7, it's going to be quite involved.  I don't feel entirely comfortable putting that on someone who isn't doing this professionally and being paid to work on npm.

Please do keep following this repo, though, there will definitely be interesting stuff to do!  We'll try to make sure to tag good intro issues as they come up.
