### ISSUE TITLE
Interesting change from npm v6: install with no shrinkwrap does a full update

### ISSUE THREAD

**Issue by isaacs** [npm/arborist#79]
In Arborist, if there's no package-lock.json, and you run `reify()` with no options, its default behavior is to build an ideal tree without consulting the actual tree, and without the guidance of a lockfile, meaning:

- It'll always update anything that can be updated, including nested transitive deps.
- It'll need to do a full tree diff, fetching all the packuments, selecting versions, etc.  More work = more time.

I'm not sure if this is a feature or bug, tbh.  It might be fine to say "if you want to lock down your deps, use a lockfile, it's right there in the name".  However, it _is_ a change, and one that's likely to have some ripple effects, the biggest of which will be lockfile abstainers complaining that `npm install` got slower.

Another approach would be to pass an option to buildIdealTree to say, if you can't load a virtualTree, then load the actualTree, and only make the changes necessary at each stage to correct problems or make user-specified changes.

If we decide this is a bug, the fix is pretty easy:

```patch
diff --git a/lib/arborist/build-ideal-tree.js b/lib/arborist/build-ideal-tree.js
index 7246e92..1f5ecd4 100644
--- a/lib/arborist/build-ideal-tree.js
+++ b/lib/arborist/build-ideal-tree.js
@@ -210,6 +210,14 @@ module.exports = cls => class IdealTreeBuilder extends Tracker(Virtual(Actual(cl
             .then(meta => Object.assign(root, {meta}))
         : this.loadVirtual({ root }))
 
+      // if we don't have a lockfile to go from, then start with the
+      // actual tree, so we only make the minimum required changes.
+      .then(async root => {
+        if (!this[_updateAll] && !tree.meta.loadedFromDisk)
+          await new this.constructor(this.options).loadActual({ root })
+        return root
+      })
+
       .then(tree => this[_mapWorkspaces](tree))
       .then(tree => {
         // null the virtual tree, because we're about to hack away at it

```

**Comment by isaacs** [comment]
One hazard here is that reify calls `loadActual` and `buildIdealTree` in _parallel_, so we'll need to make sure the actual tree is actually done before proceeding.  Ie, make `loadActual` parallel-safe by stashing a loading promise, and resolving it at the end.

**Comment by ruyadorno** [comment]
what if instead of:
> its default behavior is to build an ideal tree without consulting the actual tree

it builds an ideal tree consulting **only** the hidden lockfile?

that would avoid the problem of having `npm install` being slower to lockfile deniers, _right_?

**Comment by isaacs** [comment]
Yeah, after the first time npm v7 reifies the tree, there'll be a hidden lockfile, so it'll be reasonably fast.  (I do need to add the thing to have the hidden lockfile only load if it's newer than any of the package directories it covers, for safety, but it'll still be the default in normal cases.)

And actually, since the patch above is loading the actual tree on a new Arborist instance (to avoid mucking up the `actualTree` that `reify()` will use), the parallel safety isn't an issue.
